export interface ExamCategory {
  id: string;
  name: string;
  shortName: string;
  description: string;
  icon: string;
  color: string;
  isNational: boolean;
  examMonth: number | null;
  subjects: ExamSubject[];
  hasEssay: boolean; // 論述式があるか
}

export interface ExamSubject {
  id: string;
  name: string;
  topics: string[];
}

export const EXAM_CATEGORIES: ExamCategory[] = [
  // === 法律系 ===
  {
    id: "yobi-shihou",
    name: "司法試験予備試験",
    shortName: "予備試験",
    description: "法曹への最短ルート。短答+論文+口述の3段階",
    icon: "",
    color: "#6366f1",
    isNational: true,
    examMonth: 7,
    hasEssay: true,
    subjects: [
      { id: "kenpo", name: "憲法", topics: ["人権", "統治機構", "違憲審査基準", "判例"] },
      { id: "minpo", name: "民法", topics: ["総則", "物権", "債権", "親族・相続"] },
      { id: "keiho", name: "刑法", topics: ["総論", "各論", "構成要件", "違法性・責任"] },
      { id: "shoho", name: "商法", topics: ["会社法", "商行為", "手形・小切手"] },
      { id: "minsosho", name: "民事訴訟法", topics: ["訴訟要件", "証拠", "判決効"] },
      { id: "keisosho", name: "刑事訴訟法", topics: ["捜査", "公訴", "証拠法"] },
      { id: "gyosei", name: "行政法", topics: ["行政行為", "行政救済", "行政組織"] },
      { id: "ippan", name: "一般教養", topics: ["人文科学", "社会科学", "自然科学"] },
    ],
  },
  {
    id: "shihou-shiken",
    name: "司法試験",
    shortName: "司法試験",
    description: "法曹三者（裁判官・検察官・弁護士）の国家試験",
    icon: "",
    color: "#6366f1",
    isNational: true,
    examMonth: 7,
    hasEssay: true,
    subjects: [
      { id: "kenpo", name: "憲法", topics: ["人権", "統治機構", "違憲審査基準"] },
      { id: "minpo", name: "民法", topics: ["総則", "物権", "債権", "親族・相続"] },
      { id: "keiho", name: "刑法", topics: ["総論", "各論"] },
      { id: "shoho", name: "商法", topics: ["会社法", "商行為"] },
      { id: "minsosho", name: "民事訴訟法", topics: ["訴訟要件", "証拠", "判決効"] },
      { id: "keisosho", name: "刑事訴訟法", topics: ["捜査", "公訴", "証拠法"] },
      { id: "gyosei", name: "行政法", topics: ["行政行為", "行政救済"] },
      { id: "sentaku", name: "選択科目", topics: ["倒産法", "租税法", "経済法", "知財法", "労働法", "環境法", "国際関係法"] },
    ],
  },
  // === 会計・経営系 ===
  {
    id: "shindan-shi",
    name: "中小企業診断士",
    shortName: "診断士",
    description: "経営コンサルの国家資格。1次+2次（記述式）",
    icon: "",
    color: "#f59e0b",
    isNational: true,
    examMonth: 10,
    hasEssay: true,
    subjects: [
      { id: "keizai", name: "経済学・経済政策", topics: ["ミクロ経済", "マクロ経済", "経済政策"] },
      { id: "zaimu", name: "財務・会計", topics: ["簿記", "財務分析", "投資評価", "企業価値"] },
      { id: "kigyou", name: "企業経営理論", topics: ["経営戦略", "組織論", "マーケティング"] },
      { id: "unei", name: "運営管理", topics: ["生産管理", "店舗管理", "物流"] },
      { id: "houbu", name: "経営法務", topics: ["会社法", "知的財産", "契約"] },
      { id: "jouhou", name: "経営情報システム", topics: ["IT基礎", "システム開発", "情報セキュリティ"] },
      { id: "seisaku", name: "中小企業経営・政策", topics: ["中小企業白書", "政策", "支援制度"] },
      { id: "jirei", name: "2次試験（事例I〜IV）", topics: ["組織・人事", "マーケティング", "生産・技術", "財務・会計"] },
    ],
  },
  {
    id: "kounin-kaikeishi",
    name: "公認会計士",
    shortName: "会計士",
    description: "会計・監査のプロフェッショナル資格",
    icon: "",
    color: "#10b981",
    isNational: true,
    examMonth: 8,
    hasEssay: true,
    subjects: [
      { id: "boki", name: "簿記", topics: ["商業簿記", "工業簿記", "連結会計"] },
      { id: "zaimu-shohyo", name: "財務会計論", topics: ["会計基準", "財務諸表", "開示制度"] },
      { id: "kanri", name: "管理会計論", topics: ["原価計算", "意思決定", "業績管理"] },
      { id: "kansa", name: "監査論", topics: ["監査基準", "内部統制", "監査手続"] },
      { id: "kigyou-hou", name: "企業法", topics: ["会社法", "金融商品取引法"] },
      { id: "zeimu", name: "租税法", topics: ["法人税", "所得税", "消費税"] },
      { id: "sentaku", name: "選択科目", topics: ["経営学", "経済学", "民法", "統計学"] },
    ],
  },
  // === 不動産・行政系 ===
  {
    id: "takken",
    name: "宅地建物取引士",
    shortName: "宅建",
    description: "不動産取引の必須国家資格。受験者20万人超",
    icon: "",
    color: "#8b5cf6",
    isNational: true,
    examMonth: 10,
    hasEssay: false,
    subjects: [
      // 権利関係（14問）— 民法・借地借家法・区分所有法・不動産登記法
      { id: "minpo-souoku", name: "民法総則", topics: [
        "制限行為能力者（未成年者・成年被後見人・被保佐人・被補助人）",
        "意思表示（心裡留保・虚偽表示）",
        "意思表示（錯誤）",
        "意思表示（詐欺・強迫）",
        "代理の基本（有権代理・代理権の範囲・復代理）",
        "無権代理（無権代理人の責任・相手方の催告権・取消権）",
        "表見代理（109条・110条・112条）",
        "時効（取得時効）",
        "時効（消滅時効・時効の完成猶予と更新）",
        "条件・期限・期間の計算",
      ]},
      { id: "minpo-bukken", name: "物権", topics: [
        "物権変動（意思主義・176条）",
        "不動産の対抗要件（177条・登記）",
        "動産の対抗要件（178条・引渡し）",
        "即時取得（192条）",
        "共有（持分・管理・分割）",
        "所有権の取得（付合・混和・加工）",
        "占有権（占有の態様・回収の訴え）",
        "地上権・地役権",
        "用益物権と担保物権の全体像",
      ]},
      { id: "minpo-tanpo", name: "担保物権", topics: [
        "留置権（成立要件・効力・消滅）",
        "先取特権（種類・順位）",
        "質権（動産質・不動産質・権利質）",
        "抵当権の基本（設定・効力の及ぶ範囲・被担保債権の範囲）",
        "抵当権の順位（順位の変更・譲渡・放棄）",
        "法定地上権（成立要件・判例）",
        "一括競売・抵当権と賃借権の関係",
        "物上代位（目的・差押えの要否・判例）",
        "根抵当権（元本確定・極度額・譲渡）",
        "抵当権の処分（転抵当・譲渡・放棄・順位の譲渡・放棄）",
      ]},
      { id: "minpo-saiken-souron", name: "債権総論", topics: [
        "債務不履行（履行遅滞・履行不能・不完全履行）",
        "損害賠償（予定・過失相殺・金銭債務の特則）",
        "債権者代位権（要件・効果・転用）",
        "詐害行為取消権（要件・効果・期間制限）",
        "連帯債務（成立・求償・絶対的効力事由）",
        "保証債務（成立・性質・催告の抗弁権・検索の抗弁権）",
        "連帯保証（催告・検索の抗弁権なし）",
        "債権譲渡（対抗要件・異議をとどめない承諾）",
        "弁済（第三者弁済・弁済による代位・受領権者としての外観）",
        "相殺（要件・禁止事由・差押えとの関係）",
      ]},
      { id: "minpo-keiyaku", name: "契約各論", topics: [
        "契約の成立（申込みと承諾・懸賞広告）",
        "契約の解除（催告解除・無催告解除・解除の効果）",
        "危険負担（債務者主義・536条）",
        "同時履行の抗弁権（533条・適用場面）",
        "売買（契約不適合責任・手付・買戻し）",
        "贈与（書面・負担付贈与・死因贈与）",
        "請負（担保責任・注文者の解除権・報酬の支払時期）",
        "委任（善管注意義務・報酬・解除）",
        "賃貸借（民法の規定・存続期間・修繕義務・転貸借）",
        "使用貸借（成立・終了・貸主の死亡）",
      ]},
      { id: "minpo-fuhou", name: "不法行為・その他", topics: [
        "一般不法行為（709条・要件・効果）",
        "使用者責任（715条・求償権）",
        "工作物責任（717条・占有者と所有者の責任）",
        "共同不法行為（719条・連帯責任）",
        "不当利得（703条・704条・特殊な不当利得）",
        "事務管理",
      ]},
      { id: "minpo-shinzoku-souzoku", name: "親族・相続", topics: [
        "相続人の範囲と順位（配偶者・子・直系尊属・兄弟姉妹）",
        "代襲相続（要件・再代襲・欠格と廃除の違い）",
        "法定相続分の計算（配偶者と子・直系尊属・兄弟姉妹）",
        "遺産分割（協議・審判・遺産分割前の処分）",
        "相続の承認と放棄（単純承認・限定承認・放棄の期間と効果）",
        "遺言（自筆証書・公正証書・秘密証書・検認）",
        "遺留分（権利者・割合・遺留分侵害額請求権）",
        "配偶者居住権（成立・存続期間・登記）",
      ]},
      { id: "shakuchi-shakka", name: "借地借家法", topics: [
        "借地権の存続期間（当初30年・更新1回目20年・以後10年）",
        "借地権の更新（法定更新・建物再築と更新）",
        "借地上の建物の再築（地主の承諾・裁判所の許可）",
        "定期借地権（一般定期・事業用定期・建物譲渡特約付）",
        "借家権の存続期間と更新（正当事由・法定更新）",
        "定期建物賃貸借（公正証書等の書面・事前説明書面・終了通知）",
        "造作買取請求権",
        "借地借家法の強行規定と特約の効力",
        "転貸借・借地権の譲渡（地主の承諾・裁判所の許可代諾）",
      ]},
      { id: "kubun-touki", name: "区分所有法・不動産登記法", topics: [
        "区分所有法（専有部分・共用部分・敷地利用権）",
        "区分所有法（管理組合・集会・議決権の割合）",
        "区分所有法（規約の設定変更・管理者・義務違反者への措置）",
        "区分所有法（建替え決議・復旧決議）",
        "不動産登記法（登記の種類・対抗力・公信力なし）",
        "不動産登記法（登記手続き・仮登記・登記識別情報）",
      ]},
      // 宅建業法（20問）— 最重要科目
      { id: "takken-menkyo", name: "宅建業法（免許・宅建士）", topics: [
        "宅地建物取引業の定義（宅地の定義・取引の定義・業の定義）",
        "免許の区分（大臣免許・知事免許）と免許換え",
        "免許の欠格事由（人的要件）",
        "免許の欠格事由（法人・役員・政令使用人）",
        "免許の有効期間と更新",
        "宅建士の登録（要件・欠格事由・登録の移転）",
        "宅建士証（交付・更新・提示義務）",
        "事務所の設置（事務所の定義・届出・専任の宅建士の設置義務）",
      ]},
      { id: "takken-eigyou", name: "宅建業法（営業保証金・保証協会）", topics: [
        "営業保証金（供託額・供託所・届出・事業開始）",
        "営業保証金の還付（還付対象者・不足額の供託）",
        "営業保証金の取戻し（事由・公告義務）",
        "保証協会（加入・弁済業務保証金分担金の納付額）",
        "保証協会（弁済業務・還付・還付充当金）",
        "営業保証金と保証協会の比較整理",
      ]},
      { id: "takken-baikai", name: "宅建業法（媒介契約・広告規制）", topics: [
        "媒介契約の種類（一般・専任・専属専任の比較）",
        "媒介契約の規制（有効期間・報告義務・レインズ登録義務）",
        "報酬の限度額（売買・交換・賃借の計算方法）",
        "広告の規制（誇大広告の禁止・広告開始時期の制限）",
        "業務上の規制（契約締結時期の制限・不当な勧誘の禁止）",
      ]},
      { id: "takken-35jou", name: "宅建業法（重要事項説明・35条）", topics: [
        "重要事項説明の基本（説明の主体・相手方・時期・方法）",
        "35条の記載事項（登記された権利・法令上の制限・インフラ整備状況）",
        "35条の記載事項（代金以外の金銭・契約解除・損害賠償額の予定）",
        "35条の記載事項（手付金等の保全措置・ローンのあっせん）",
        "35条の記載事項（貸借特有の事項）",
        "IT重説の要件と手続き",
      ]},
      { id: "takken-37jou", name: "宅建業法（37条書面）", topics: [
        "37条書面の必要的記載事項",
        "37条書面の任意的記載事項",
        "35条書面と37条書面の比較整理",
        "37条書面の交付の相手方と宅建士の記名",
      ]},
      { id: "takken-8shu", name: "宅建業法（8種制限）", topics: [
        "8種制限の適用場面（業者売主・非業者買主の場合のみ）",
        "クーリングオフ（適用場面・期間・方法・効果）",
        "損害賠償額の予定等の制限（代金の20%）",
        "手付の性質と額の制限（解約手付・代金の20%）",
        "手付金等の保全措置（未完成物件5%・完成物件10%）",
        "自己の所有に属しない物件の売買制限",
        "契約不適合責任の特約制限（引渡しから2年以上）",
        "割賦販売の契約解除等の制限",
        "所有権留保等の禁止",
      ]},
      { id: "takken-kantoku", name: "宅建業法（監督処分・住宅瑕疵担保履行法）", topics: [
        "監督処分（指示処分・業務停止処分・免許取消処分）",
        "罰則（罰金・懲役の主な適用場面）",
        "住宅瑕疵担保履行法（資力確保措置・供託・保険）",
      ]},
      // 法令上の制限（8問）
      { id: "toshi-keikaku", name: "都市計画法", topics: [
        "都市計画の体系（都市計画区域・準都市計画区域・区域外）",
        "区域区分（市街化区域・市街化調整区域）",
        "用途地域（13種類の概要と指定できる区域）",
        "地域地区（特別用途地区・高度地区・高度利用地区・特定街区等）",
        "都市施設・市街地開発事業",
        "地区計画",
        "開発許可制度（開発行為の定義・許可の要否）",
        "開発許可の基準（33条基準・34条基準）",
        "開発許可後の手続き（工事完了の届出・検査済証・公告前の建築制限）",
        "都市計画の決定手続きと都市計画制限",
      ]},
      { id: "kenchiku-kijun", name: "建築基準法", topics: [
        "建築確認（必要な建築物・手続き・検査）",
        "用途制限（13種類の用途地域ごとの建築可能な建物）",
        "道路制限（接道義務・4m未満のみなし道路・セットバック）",
        "建蔽率（計算方法・角地緩和・防火地域の緩和・適用除外）",
        "容積率（計算方法・前面道路幅員による制限・特定道路の緩和）",
        "高さ制限（絶対高さ制限・斜線制限・日影規制）",
        "防火地域・準防火地域（建築物の構造制限）",
        "建築協定",
        "単体規定（構造耐力・防火・避難・採光・換気）",
        "既存不適格建築物",
      ]},
      { id: "hourei-sonota", name: "その他の法令上の制限", topics: [
        "国土利用計画法（事後届出制・届出対象面積・届出先・届出期間）",
        "農地法（3条許可・4条許可・5条許可・市街化区域の特例）",
        "土地区画整理法（施行者・仮換地・換地処分・清算金）",
        "宅地造成及び特定盛土等規制法（規制区域・許可・届出）",
        "その他の法令（生産緑地法・河川法・自然公園法・文化財保護法等）",
      ]},
      // 税・その他（8問）
      { id: "fudousan-zei", name: "不動産に関する税金", topics: [
        "不動産取得税（課税主体・税率・課税標準・特例・免税点）",
        "固定資産税（納税義務者・税率・住宅用地の特例・新築住宅の減額）",
        "登録免許税（税率・軽減税率・納付方法）",
        "印紙税（課税文書・税額・非課税文書・過怠税）",
        "所得税（譲渡所得・長期と短期・3,000万円特別控除・買換え特例・住宅ローン控除）",
        "贈与税・相続税（住宅取得等資金の非課税）",
      ]},
      { id: "kantei-sonota", name: "地価公示・鑑定評価・その他", topics: [
        "地価公示法（目的・標準地・公示価格・効力）",
        "不動産鑑定評価基準（原価法・取引事例比較法・収益還元法）",
        "住宅金融支援機構（フラット35・直接融資）",
        "景品表示法（不動産の表示に関する公正競争規約）",
        "統計問題の出題パターンと対策",
        "土地の形質・地目・種類の知識",
        "建物の構造・材料・設備の知識",
      ]},
    ],
  },
  {
    id: "gyousei-shoshi",
    name: "行政書士",
    shortName: "行政書士",
    description: "行政手続の専門家。記述式あり",
    icon: "",
    color: "#ec4899",
    isNational: true,
    examMonth: 11,
    hasEssay: true,
    subjects: [
      { id: "kiso-hourei", name: "基礎法学", topics: ["法の概念", "法体系", "法解釈"] },
      { id: "kenpo-gs", name: "憲法", topics: ["人権", "統治", "判例"] },
      { id: "gyosei-hou", name: "行政法", topics: ["行政手続法", "行政不服審査法", "行政事件訴訟法", "国家賠償法", "地方自治法"] },
      { id: "minpo-gs", name: "民法", topics: ["総則", "物権", "債権", "親族・相続"] },
      { id: "shoho-gs", name: "商法・会社法", topics: ["商法総則", "会社法"] },
      { id: "ippan-chishiki", name: "一般知識", topics: ["政治・経済・社会", "情報通信", "文章理解"] },
    ],
  },
  {
    id: "sharoshi",
    name: "社会保険労務士",
    shortName: "社労士",
    description: "労働・社会保険の専門家",
    icon: "",
    color: "#0ea5e9",
    isNational: true,
    examMonth: 8,
    hasEssay: false,
    subjects: [
      { id: "roudou-kijun", name: "労働基準法", topics: ["労働時間", "賃金", "解雇", "就業規則"] },
      { id: "anzen-eisei", name: "労働安全衛生法", topics: ["安全管理", "健康診断", "ストレスチェック"] },
      { id: "rousai", name: "労災保険法", topics: ["業務災害", "通勤災害", "給付"] },
      { id: "koyou", name: "雇用保険法", topics: ["失業等給付", "育児・介護", "教育訓練"] },
      { id: "kenkou-hoken", name: "健康保険法", topics: ["被保険者", "給付", "保険料"] },
      { id: "kokumin-nenkin", name: "国民年金法", topics: ["被保険者", "老齢基礎年金", "障害・遺族"] },
      { id: "kousei-nenkin", name: "厚生年金保険法", topics: ["被保険者", "老齢厚生年金", "在職老齢"] },
      { id: "ippan-joko", name: "一般常識", topics: ["労務管理", "社会保険", "統計"] },
    ],
  },
  // === 金融系 ===
  {
    id: "fp2",
    name: "FP2級（ファイナンシャルプランナー）",
    shortName: "FP2級",
    description: "お金の専門家。実技試験あり",
    icon: "",
    color: "#f97316",
    isNational: true,
    examMonth: 1, // 1月, 5月, 9月
    hasEssay: false,
    subjects: [
      { id: "life", name: "ライフプランニング", topics: ["社会保険", "年金", "住宅ローン", "教育資金"] },
      { id: "risk", name: "リスク管理", topics: ["生命保険", "損害保険", "第三分野"] },
      { id: "kinyu", name: "金融資産運用", topics: ["株式", "債券", "投資信託", "ポートフォリオ"] },
      { id: "tax", name: "タックスプランニング", topics: ["所得税", "住民税", "法人税", "消費税"] },
      { id: "fudousan", name: "不動産", topics: ["取引", "法令", "税金", "有効活用"] },
      { id: "souzoku", name: "相続・事業承継", topics: ["相続税", "贈与税", "事業承継", "財産評価"] },
    ],
  },
  // === 公務員 ===
  {
    id: "koumuin",
    name: "公務員試験（国家一般・地方上級）",
    shortName: "公務員",
    description: "教養+専門+論文。年間受験者数2万人超",
    icon: "",
    color: "#14b8a6",
    isNational: true,
    examMonth: 6,
    hasEssay: true,
    subjects: [
      { id: "suuri", name: "数的処理", topics: ["数的推理", "判断推理", "空間把握", "資料解釈"] },
      { id: "bunkei", name: "文章理解", topics: ["現代文", "英文", "古文"] },
      { id: "shakai-kagaku", name: "社会科学", topics: ["政治", "経済", "法律", "社会"] },
      { id: "jinbun", name: "人文科学", topics: ["日本史", "世界史", "地理", "思想"] },
      { id: "shizen", name: "自然科学", topics: ["数学", "物理", "化学", "生物", "地学"] },
      { id: "senmon", name: "専門科目", topics: ["憲法", "民法", "行政法", "経済学", "政治学"] },
      { id: "ronbun", name: "論文試験", topics: ["政策論文", "小論文"] },
    ],
  },
  // === 医療系 ===
  {
    id: "ishi",
    name: "医師国家試験",
    shortName: "医師国試",
    description: "医学部6年間の集大成。合格率約90%",
    icon: "",
    color: "#ef4444",
    isNational: true,
    examMonth: 2,
    hasEssay: false,
    subjects: [
      { id: "naikagaku", name: "内科学", topics: ["循環器", "消化器", "呼吸器", "内分泌", "腎臓", "血液", "神経"] },
      { id: "gekagaku", name: "外科学", topics: ["消化器外科", "心臓血管外科", "脳神経外科"] },
      { id: "sanfujinka", name: "産婦人科", topics: ["周産期", "婦人科腫瘍", "生殖医療"] },
      { id: "shonika", name: "小児科", topics: ["新生児", "先天異常", "感染症", "発達"] },
      { id: "kouei", name: "公衆衛生", topics: ["疫学", "統計", "医療制度", "感染症法"] },
      { id: "ippan-rinsho", name: "一般臨床", topics: ["救急", "麻酔", "放射線", "病理"] },
    ],
  },
  {
    id: "kangoshi",
    name: "看護師国家試験",
    shortName: "看護師国試",
    description: "看護学部・専門学校の国家試験",
    icon: "",
    color: "#ec4899",
    isNational: true,
    examMonth: 2,
    hasEssay: false,
    subjects: [
      { id: "kiso-kango", name: "基礎看護学", topics: ["看護概論", "基本技術", "看護過程"] },
      { id: "seijin", name: "成人看護学", topics: ["急性期", "慢性期", "終末期", "周手術期"] },
      { id: "roujin", name: "老年看護学", topics: ["加齢変化", "認知症", "リハビリ"] },
      { id: "boshi", name: "母性看護学", topics: ["妊娠・分娩・産褥", "新生児", "女性の健康"] },
      { id: "shouni", name: "小児看護学", topics: ["成長発達", "小児疾患", "入院児の看護"] },
      { id: "seishin", name: "精神看護学", topics: ["精神疾患", "治療", "社会復帰"] },
      { id: "zaitaku", name: "在宅看護論", topics: ["訪問看護", "在宅医療", "地域連携"] },
      { id: "kenko-shien", name: "健康支援と社会保障", topics: ["公衆衛生", "社会保障", "関係法規"] },
    ],
  },
  // === IT・情報処理 ===
  {
    id: "it-passport",
    name: "ITパスポート試験",
    shortName: "ITパスポート",
    description: "IT系国家資格の登竜門。全社会人に推奨される基礎的IT力",
    icon: "",
    color: "#6366f1",
    isNational: true,
    examMonth: null, // CBT方式で通年
    hasEssay: false,
    subjects: [
      { id: "strategy", name: "ストラテジ系", topics: ["企業活動", "法務", "経営戦略", "システム戦略", "マーケティング"] },
      { id: "management", name: "マネジメント系", topics: ["プロジェクトマネジメント", "サービスマネジメント", "システム監査"] },
      { id: "technology", name: "テクノロジ系", topics: ["基礎理論", "アルゴリズム", "コンピュータシステム", "技術要素", "セキュリティ", "ネットワーク", "データベース"] },
    ],
  },
  {
    id: "kihon-jouhou",
    name: "基本情報技術者試験",
    shortName: "基本情報",
    description: "ITエンジニアの登竜門。科目A+科目Bの2部構成",
    icon: "",
    color: "#6366f1",
    isNational: true,
    examMonth: null, // CBT通年
    hasEssay: false,
    subjects: [
      { id: "kiso-riron", name: "基礎理論", topics: ["離散数学", "応用数学", "アルゴリズム", "プログラミング", "データ構造"] },
      { id: "computer", name: "コンピュータシステム", topics: ["プロセッサ", "メモリ", "OS", "ハードウェア", "ソフトウェア"] },
      { id: "gijutsu", name: "技術要素", topics: ["データベース", "ネットワーク", "セキュリティ", "マルチメディア"] },
      { id: "kaihatsu", name: "開発技術", topics: ["システム開発", "ソフトウェア開発", "テスト手法", "開発プロセス"] },
      { id: "management-ki", name: "マネジメント", topics: ["プロジェクトマネジメント", "サービスマネジメント", "システム監査"] },
      { id: "strategy-ki", name: "ストラテジ", topics: ["システム戦略", "経営戦略", "企業と法務"] },
      { id: "kamoku-b", name: "科目B（アルゴリズム）", topics: ["擬似言語", "トレース", "データ構造操作", "セキュリティ実践"] },
    ],
  },
  // === 会計・簿記 ===
  {
    id: "boki2",
    name: "日商簿記検定2級",
    shortName: "簿記2級",
    description: "経理・会計の実務レベル資格。商業簿記+工業簿記",
    icon: "",
    color: "#10b981",
    isNational: false,
    examMonth: null, // 年3回 + CBT
    hasEssay: false,
    subjects: [
      { id: "shogyo-boki", name: "商業簿記", topics: ["仕訳", "決算整理", "財務諸表作成", "連結会計", "税効果会計", "リース会計", "外貨建取引"] },
      { id: "kogyo-boki", name: "工業簿記", topics: ["費目別計算", "部門別計算", "個別原価計算", "総合原価計算", "標準原価計算", "直接原価計算", "CVP分析"] },
    ],
  },
  {
    id: "boki3",
    name: "日商簿記検定3級",
    shortName: "簿記3級",
    description: "簿記の基礎。就職・転職で評価される入門資格",
    icon: "",
    color: "#10b981",
    isNational: false,
    examMonth: null,
    hasEssay: false,
    subjects: [
      { id: "boki-kiso", name: "簿記の基礎", topics: ["仕訳", "勘定記入", "試算表", "精算表", "財務諸表"] },
      { id: "shiwake", name: "取引と仕訳", topics: ["現金・預金", "売掛金・買掛金", "手形", "有価証券", "固定資産", "貸倒引当金", "減価償却"] },
      { id: "kessan", name: "決算", topics: ["決算整理仕訳", "精算表作成", "損益計算書", "貸借対照表", "繰越試算表"] },
    ],
  },
  // === 販売・流通 ===
  {
    id: "touroku-hanbai",
    name: "登録販売者試験",
    shortName: "登録販売者",
    description: "一般用医薬品の販売に必須。ドラッグストア等で需要大",
    icon: "",
    color: "#ec4899",
    isNational: true,
    examMonth: 8, // 都道府県により異なるが8-12月
    hasEssay: false,
    subjects: [
      { id: "iyakuhin-kiso", name: "医薬品に共通する特性と基本的な知識", topics: ["医薬品概論", "副作用", "適正使用", "薬害の歴史"] },
      { id: "jinntai", name: "人体の働きと医薬品", topics: ["消化器系", "呼吸器系", "循環器系", "泌尿器系", "感覚器", "皮膚", "中枢神経系"] },
      { id: "syuyaku", name: "主な医薬品とその作用", topics: ["かぜ薬", "解熱鎮痛薬", "胃腸薬", "アレルギー用薬", "皮膚用薬", "点眼薬", "漢方薬"] },
      { id: "yakuji-hourei", name: "薬事関連法規・制度", topics: ["医薬品医療機器等法", "販売業の許可", "販売制度", "リスク区分"] },
      { id: "tekisei-shiyo", name: "医薬品の適正使用・安全対策", topics: ["添付文書の読み方", "副作用報告制度", "医薬品副作用被害救済制度"] },
    ],
  },
  // === 入試（既存機能の拡張） ===
  {
    id: "daigaku-nyushi",
    name: "大学入試（小論文・志望理由書）",
    shortName: "大学入試",
    description: "小論文・志望理由書・自己推薦書の添削",
    icon: "",
    color: "#e11d48",
    isNational: false,
    examMonth: null,
    hasEssay: true,
    subjects: [
      { id: "shoronbun", name: "小論文", topics: ["社会問題", "科学技術", "教育", "国際関係"] },
      { id: "shibou-riyu", name: "志望理由書", topics: ["AO入試", "推薦入試", "総合型選抜"] },
      { id: "jiko-suisen", name: "自己推薦書", topics: ["活動実績", "将来ビジョン"] },
    ],
  },
  {
    id: "daigaku-report",
    name: "大学レポート",
    shortName: "大学レポート",
    description: "大学の各種レポート・論文の添削",
    icon: "",
    color: "#e11d48",
    isNational: false,
    examMonth: null,
    hasEssay: true,
    subjects: [
      { id: "ronsho", name: "論証型レポート", topics: ["法学", "経済学", "社会学"] },
      { id: "jikken", name: "実験レポート", topics: ["理工系", "IMRAD構造"] },
      { id: "bunken", name: "文献レビュー", topics: ["先行研究", "批判的検討"] },
    ],
  },
  // === ビジネス・経営（追加） ===
  {
    id: "gijutsu-shi",
    name: "技術士",
    shortName: "技術士",
    description: "科学技術の最高峰国家資格。21の技術部門",
    icon: "",
    color: "#6366f1",
    isNational: true,
    examMonth: 7,
    hasEssay: true,
    subjects: [
      { id: "kiso", name: "基礎科目", topics: ["設計・計画", "情報・論理", "解析", "材料・化学・バイオ", "環境・エネルギー"] },
      { id: "tekisei", name: "適性科目", topics: ["技術者倫理", "技術士法", "公益確保", "持続可能性"] },
      { id: "senmon", name: "専門科目", topics: ["選択部門の専門知識"] },
      { id: "ronbun", name: "論文試験", topics: ["技術的体験論文", "課題解決能力"] },
    ],
  },
  {
    id: "hanbaishi",
    name: "販売士（リテールマーケティング検定）",
    shortName: "販売士",
    description: "流通・小売の実務資格。2級・3級",
    icon: "",
    color: "#f59e0b",
    isNational: false,
    examMonth: 7,
    hasEssay: false,
    subjects: [
      { id: "kouri", name: "小売業の類型", topics: ["組織形態", "チェーンストア", "商業集積"] },
      { id: "md", name: "マーチャンダイジング", topics: ["商品計画", "販売計画", "在庫管理", "価格設定"] },
      { id: "store-op", name: "ストアオペレーション", topics: ["店舗運営", "人的販売", "ディスプレイ"] },
      { id: "marketing", name: "マーケティング", topics: ["市場調査", "販売促進", "顧客管理"] },
      { id: "hanbai-keiei", name: "販売・経営管理", topics: ["販売管理者の役割", "従業員管理", "経営分析"] },
    ],
  },
  {
    id: "kikenbutsu",
    name: "危険物取扱者（乙種第4類）",
    shortName: "危険物乙4",
    description: "ガソリン等の引火性液体を扱う必須資格",
    icon: "",
    color: "#ef4444",
    isNational: true,
    examMonth: null,
    hasEssay: false,
    subjects: [
      { id: "hourei", name: "危険物に関する法令", topics: ["消防法", "指定数量", "貯蔵・取扱", "運搬・移送", "設置許可"] },
      { id: "butsurika", name: "基礎的な物理学及び基礎的な化学", topics: ["物質の状態変化", "燃焼理論", "消火理論", "静電気"] },
      { id: "seishitsu", name: "危険物の性質並びにその火災予防及び消火の方法", topics: ["第4類の性質", "引火点・発火点", "消火方法"] },
    ],
  },
  {
    id: "mental-health",
    name: "メンタルヘルス・マネジメント検定",
    shortName: "メンタルヘルス",
    description: "職場のメンタルヘルスケア。II種・III種",
    icon: "",
    color: "#8b5cf6",
    isNational: false,
    examMonth: 11,
    hasEssay: false,
    subjects: [
      { id: "kiso-chishiki", name: "メンタルヘルスケアの意義", topics: ["ストレス理論", "メンタルヘルスの現状", "法的背景"] },
      { id: "stress", name: "ストレスおよびメンタルヘルスに関する基礎知識", topics: ["ストレス要因", "ストレス反応", "うつ病", "適応障害"] },
      { id: "self-care", name: "セルフケア", topics: ["ストレスへの気づき", "リラクゼーション", "相談体制"] },
      { id: "line-care", name: "ラインケア", topics: ["部下の変化への気づき", "職場環境改善", "復職支援"] },
    ],
  },
  // === 不動産・建築（追加） ===
  {
    id: "kenchiku-shi",
    name: "建築士（二級）",
    shortName: "建築士",
    description: "建築設計・工事監理の国家資格",
    icon: "",
    color: "#8b5cf6",
    isNational: true,
    examMonth: 7,
    hasEssay: false,
    subjects: [
      { id: "keikaku", name: "建築計画", topics: ["住宅", "公共建築", "環境工学", "建築史"] },
      { id: "hourei-k", name: "建築法規", topics: ["建築基準法", "都市計画法", "消防法", "バリアフリー法"] },
      { id: "kouzou", name: "建築構造", topics: ["力学", "RC造", "鉄骨造", "木造", "基礎構造"] },
      { id: "sekou", name: "建築施工", topics: ["施工計画", "各部工事", "品質管理", "安全管理"] },
    ],
  },
  {
    id: "mankan",
    name: "マンション管理士/管理業務主任者",
    shortName: "マン管",
    description: "マンション管理の専門家。ダブル受験が主流",
    icon: "",
    color: "#8b5cf6",
    isNational: true,
    examMonth: 11,
    hasEssay: false,
    subjects: [
      { id: "kuhou", name: "区分所有法", topics: ["共用部分", "管理組合", "規約", "集会", "建替え"] },
      { id: "minka", name: "民法・その他の法令", topics: ["契約", "不法行為", "都市計画法", "建築基準法"] },
      { id: "kanri-jitsumu", name: "管理実務", topics: ["会計", "長期修繕計画", "委託契約", "保険"] },
      { id: "setsubi", name: "建築・設備", topics: ["RC構造", "給排水", "電気設備", "消防設備"] },
    ],
  },
  {
    id: "chintai",
    name: "賃貸不動産経営管理士",
    shortName: "賃管",
    description: "賃貸住宅管理の国家資格",
    icon: "",
    color: "#8b5cf6",
    isNational: true,
    examMonth: 11,
    hasEssay: false,
    subjects: [
      { id: "kanri-sougou", name: "管理業務総論", topics: ["賃貸住宅管理業法", "登録制度", "業務管理者"] },
      { id: "chintai-keiyaku", name: "賃貸借契約", topics: ["借地借家法", "契約の成立", "更新", "解約", "原状回復"] },
      { id: "kanri-jitsumu-c", name: "管理実務", topics: ["入居者管理", "建物管理", "設備管理", "清掃"] },
      { id: "kanri-keiei", name: "賃貸経営", topics: ["市場調査", "企画提案", "税金", "保険"] },
    ],
  },
  // === 法律・労務（追加） ===
  {
    id: "shihou-shoshi",
    name: "司法書士",
    shortName: "司法書士",
    description: "登記・供託・訴訟代理の法律専門家",
    icon: "",
    color: "#6366f1",
    isNational: true,
    examMonth: 7,
    hasEssay: true,
    subjects: [
      { id: "minpo-ss", name: "民法", topics: ["総則", "物権", "担保物権", "債権", "親族・相続"] },
      { id: "fudousan-touki", name: "不動産登記法", topics: ["総論", "所有権", "抵当権", "信託", "区分建物"] },
      { id: "shougyou-touki", name: "商業登記法", topics: ["株式会社", "設立", "役員変更", "組織再編"] },
      { id: "kaisha-hou", name: "会社法", topics: ["設立", "機関", "株式", "計算", "解散"] },
      { id: "kenpo-ss", name: "憲法", topics: ["人権", "統治機構"] },
      { id: "keiho-ss", name: "刑法", topics: ["総論", "各論"] },
      { id: "minsosho-ss", name: "民事訴訟法", topics: ["訴訟要件", "判決効", "保全・執行"] },
      { id: "kyoutaku", name: "供託法", topics: ["弁済供託", "裁判上の供託"] },
    ],
  },
  {
    id: "benri-shi",
    name: "弁理士",
    shortName: "弁理士",
    description: "知的財産の専門家。特許・商標の出願代理",
    icon: "",
    color: "#6366f1",
    isNational: true,
    examMonth: 5,
    hasEssay: true,
    subjects: [
      { id: "tokkyo", name: "特許法", topics: ["特許要件", "出願", "審査", "審判", "侵害"] },
      { id: "jitsuyo", name: "実用新案法", topics: ["登録要件", "技術評価書", "特許法との比較"] },
      { id: "ishou", name: "意匠法", topics: ["意匠登録要件", "部分意匠", "関連意匠"] },
      { id: "shouhyou", name: "商標法", topics: ["登録要件", "商標の類似", "不使用取消審判"] },
      { id: "jouhou-hou", name: "条約", topics: ["パリ条約", "PCT", "マドリッド協定"] },
      { id: "fuseikyousou", name: "不正競争防止法・著作権法", topics: ["不正競争行為", "著作物", "著作者の権利"] },
    ],
  },
  {
    id: "business-law",
    name: "ビジネス実務法務検定試験",
    shortName: "ビジ法",
    description: "ビジネスに必要な法律知識。2級・3級",
    icon: "",
    color: "#6366f1",
    isNational: false,
    examMonth: 6,
    hasEssay: false,
    subjects: [
      { id: "keiyaku-bl", name: "取引を行う主体", topics: ["権利能力", "意思能力", "法人", "代理"] },
      { id: "torihiki", name: "取引と契約", topics: ["契約の成立", "売買", "請負", "委任", "債務不履行"] },
      { id: "saiken", name: "債権の管理・回収", topics: ["担保", "保証", "相殺", "時効", "倒産"] },
      { id: "kigyou-katsudou", name: "企業活動と法規制", topics: ["独占禁止法", "消費者保護法", "個人情報保護法"] },
      { id: "kaisha-bl", name: "会社に関する法律", topics: ["株主総会", "取締役", "計算書類", "組織再編"] },
      { id: "roudou-bl", name: "企業と従業員の法律", topics: ["労働契約", "就業規則", "解雇", "ハラスメント"] },
    ],
  },
  {
    id: "chizai",
    name: "知的財産管理技能検定",
    shortName: "知財検定",
    description: "知財の実務能力を測る国家技能検定",
    icon: "",
    color: "#6366f1",
    isNational: true,
    examMonth: 7,
    hasEssay: false,
    subjects: [
      { id: "tokkyo-c", name: "特許・実用新案", topics: ["出願", "権利化", "活用", "侵害対応"] },
      { id: "ishou-c", name: "意匠", topics: ["出願", "登録要件", "権利範囲"] },
      { id: "shouhyou-c", name: "商標", topics: ["出願", "審査", "使用権", "類似判断"] },
      { id: "chosakuken-c", name: "著作権", topics: ["著作物", "著作者", "利用許諾", "侵害"] },
      { id: "fuseikyousou-c", name: "不正競争防止・その他", topics: ["営業秘密", "種苗法", "ドメイン名"] },
    ],
  },
  {
    id: "kojin-joho",
    name: "個人情報保護士",
    shortName: "個人情報保護士",
    description: "個人情報保護法の専門知識を証明",
    icon: "",
    color: "#6366f1",
    isNational: false,
    examMonth: 6,
    hasEssay: false,
    subjects: [
      { id: "horei-pii", name: "個人情報保護法の理解", topics: ["定義", "取得", "利用", "提供", "開示請求", "罰則"] },
      { id: "my-number", name: "マイナンバー法", topics: ["番号法の概要", "特定個人情報", "安全管理措置"] },
      { id: "kanri", name: "個人情報保護の対策と情報セキュリティ", topics: ["組織的安全管理", "技術的安全管理", "物理的安全管理"] },
    ],
  },
  // === IT（追加） ===
  {
    id: "sg",
    name: "情報セキュリティマネジメント試験",
    shortName: "セキュマネ",
    description: "情報セキュリティの国家試験。午前+午後",
    icon: "",
    color: "#6366f1",
    isNational: true,
    examMonth: null,
    hasEssay: false,
    subjects: [
      { id: "security-kiso", name: "情報セキュリティ基礎", topics: ["脅威", "脆弱性", "攻撃手法", "暗号化", "認証"] },
      { id: "kanri-sg", name: "情報セキュリティ管理", topics: ["ISMS", "リスクアセスメント", "セキュリティポリシー"] },
      { id: "gijutsu-sg", name: "情報セキュリティ対策", topics: ["ファイアウォール", "IDS/IPS", "VPN", "マルウェア対策"] },
      { id: "hourei-sg", name: "法規", topics: ["不正アクセス禁止法", "個人情報保護法", "サイバーセキュリティ基本法"] },
    ],
  },
  {
    id: "ap",
    name: "応用情報技術者試験",
    shortName: "応用情報",
    description: "IT技術者のスキルアップ。午前+午後記述式",
    icon: "",
    color: "#6366f1",
    isNational: true,
    examMonth: 4,
    hasEssay: true,
    subjects: [
      { id: "kiso-riron-ap", name: "基礎理論", topics: ["離散数学", "アルゴリズム", "プログラミング"] },
      { id: "computer-ap", name: "コンピュータシステム", topics: ["プロセッサ", "メモリ", "OS", "ミドルウェア"] },
      { id: "gijutsu-ap", name: "技術要素", topics: ["データベース", "ネットワーク", "セキュリティ"] },
      { id: "kaihatsu-ap", name: "開発技術", topics: ["要件定義", "設計", "テスト", "プロジェクト管理"] },
      { id: "management-ap", name: "サービスマネジメント", topics: ["ITIL", "システム監査", "内部統制"] },
      { id: "strategy-ap", name: "経営戦略", topics: ["企業戦略", "IT戦略", "ビジネスインダストリ"] },
    ],
  },
  {
    id: "st",
    name: "ITストラテジスト試験",
    shortName: "ITストラテジスト",
    description: "高度IT人材。経営戦略とIT活用の融合",
    icon: "",
    color: "#6366f1",
    isNational: true,
    examMonth: 4,
    hasEssay: true,
    subjects: [
      { id: "keiei-senryaku", name: "経営戦略", topics: ["事業戦略", "競争戦略", "グローバル戦略"] },
      { id: "it-senryaku", name: "IT戦略", topics: ["IT投資", "IT組織", "EA", "SOA"] },
      { id: "jigyou-senryaku", name: "事業企画", topics: ["ビジネスモデル", "マーケティング", "イノベーション"] },
      { id: "ronbun-st", name: "論文", topics: ["IT戦略策定", "業務改革", "システム化構想"] },
    ],
  },
  {
    id: "nw",
    name: "ネットワークスペシャリスト試験",
    shortName: "ネスペ",
    description: "ネットワーク技術の高度試験",
    icon: "",
    color: "#6366f1",
    isNational: true,
    examMonth: 4,
    hasEssay: true,
    subjects: [
      { id: "nw-kiso", name: "ネットワーク基礎", topics: ["OSI参照モデル", "TCP/IP", "ルーティング", "スイッチング"] },
      { id: "nw-ouyo", name: "ネットワーク応用", topics: ["VLAN", "VPN", "無線LAN", "SDN"] },
      { id: "nw-security", name: "セキュリティ", topics: ["ファイアウォール", "PKI", "IDS/IPS", "SSL/TLS"] },
      { id: "nw-sekkei", name: "ネットワーク設計", topics: ["冗長構成", "負荷分散", "QoS", "トラフィック分析"] },
    ],
  },
  {
    id: "db",
    name: "データベーススペシャリスト試験",
    shortName: "デスペ",
    description: "データベース技術の高度試験",
    icon: "",
    color: "#6366f1",
    isNational: true,
    examMonth: 10,
    hasEssay: true,
    subjects: [
      { id: "db-kiso", name: "データベース基礎", topics: ["関係データモデル", "正規化", "ER図", "SQL"] },
      { id: "db-sekkei", name: "データベース設計", topics: ["概念設計", "論理設計", "物理設計", "パフォーマンス"] },
      { id: "db-unei", name: "データベース運用", topics: ["バックアップ", "障害回復", "性能管理", "セキュリティ"] },
      { id: "db-ouyo", name: "応用", topics: ["NoSQL", "分散DB", "データウェアハウス", "ビッグデータ"] },
    ],
  },
  {
    id: "aws",
    name: "AWS認定試験",
    shortName: "AWS認定",
    description: "Amazon Web Servicesの認定資格",
    icon: "",
    color: "#f59e0b",
    isNational: false,
    examMonth: null,
    hasEssay: false,
    subjects: [
      { id: "cloud-kiso", name: "クラウドの基礎", topics: ["リージョン", "AZ", "エッジロケーション", "責任共有モデル"] },
      { id: "compute", name: "コンピューティング", topics: ["EC2", "Lambda", "ECS", "Fargate", "Auto Scaling"] },
      { id: "storage", name: "ストレージ", topics: ["S3", "EBS", "EFS", "Glacier", "Storage Gateway"] },
      { id: "database-aws", name: "データベース", topics: ["RDS", "DynamoDB", "ElastiCache", "Redshift", "Aurora"] },
      { id: "networking", name: "ネットワーク", topics: ["VPC", "Route 53", "CloudFront", "ELB", "Direct Connect"] },
      { id: "security-aws", name: "セキュリティ", topics: ["IAM", "KMS", "WAF", "Shield", "GuardDuty"] },
    ],
  },
  {
    id: "python3",
    name: "Python 3 エンジニア認定試験",
    shortName: "Python認定",
    description: "Pythonの基礎文法・データ分析の認定",
    icon: "",
    color: "#0ea5e9",
    isNational: false,
    examMonth: null,
    hasEssay: false,
    subjects: [
      { id: "kiso-bunpou", name: "基礎文法", topics: ["変数・型", "制御構文", "関数", "クラス", "例外処理"] },
      { id: "data-structure", name: "データ構造", topics: ["リスト", "辞書", "タプル", "セット", "内包表記"] },
      { id: "standard-lib", name: "標準ライブラリ", topics: ["os", "sys", "re", "datetime", "json", "collections"] },
      { id: "data-analysis", name: "データ分析", topics: ["NumPy", "pandas", "matplotlib", "scikit-learn"] },
    ],
  },
  // === 会計・金融（追加） ===
  {
    id: "zeirishi",
    name: "税理士",
    shortName: "税理士",
    description: "税務の専門家。5科目合格で資格取得",
    icon: "",
    color: "#10b981",
    isNational: true,
    examMonth: 8,
    hasEssay: true,
    subjects: [
      { id: "boki-z", name: "簿記論", topics: ["仕訳", "決算整理", "本支店会計", "連結", "税効果"] },
      { id: "zaimu-z", name: "財務諸表論", topics: ["会計理論", "概念フレームワーク", "個別論点", "財務諸表作成"] },
      { id: "houjin-z", name: "法人税法", topics: ["所得計算", "益金", "損金", "税額計算", "申告"] },
      { id: "shotoku-z", name: "所得税法", topics: ["各種所得", "損益通算", "所得控除", "税額控除"] },
      { id: "souzoku-z", name: "相続税法", topics: ["相続税", "贈与税", "財産評価", "納税猶予"] },
      { id: "shouhi-z", name: "消費税法", topics: ["課税取引", "仕入税額控除", "簡易課税", "インボイス"] },
    ],
  },
  {
    id: "gaimuin",
    name: "外務員（証券外務員）",
    shortName: "外務員",
    description: "金融商品取引の必須資格。一種・二種",
    icon: "",
    color: "#f97316",
    isNational: false,
    examMonth: null,
    hasEssay: false,
    subjects: [
      { id: "hourei-g", name: "法令・諸規則", topics: ["金融商品取引法", "投資信託法", "協会規則", "取引所規則"] },
      { id: "shouken", name: "商品業務", topics: ["株式", "債券", "投資信託", "デリバティブ", "外国証券"] },
      { id: "kanren", name: "関連科目", topics: ["証券市場", "経済・金融", "財務諸表", "税金"] },
    ],
  },
  {
    id: "kashikin",
    name: "貸金業務取扱主任者",
    shortName: "貸金主任者",
    description: "貸金業の法令遵守を担保する必置資格",
    icon: "",
    color: "#f97316",
    isNational: true,
    examMonth: 11,
    hasEssay: false,
    subjects: [
      { id: "kashikin-hou", name: "貸金業法", topics: ["登録制度", "業務規制", "取立規制", "書面交付義務"] },
      { id: "kanren-hourei", name: "関連法令", topics: ["利息制限法", "出資法", "民法", "民事訴訟法", "倒産法"] },
      { id: "shikin", name: "資金需要者の保護", topics: ["過剰貸付防止", "個人信用情報", "総量規制"] },
      { id: "zaimu-kaikei", name: "財務・会計", topics: ["財務諸表", "経営分析", "会計処理"] },
    ],
  },
  // === 福祉 ===
  {
    id: "hoiku-shi",
    name: "保育士",
    shortName: "保育士",
    description: "保育のプロフェッショナル国家資格",
    icon: "",
    color: "#ec4899",
    isNational: true,
    examMonth: 4,
    hasEssay: false,
    subjects: [
      { id: "hoiku-genri", name: "保育原理", topics: ["保育所保育指針", "保育の歴史", "保育の目標"] },
      { id: "kyouiku-genri", name: "教育原理", topics: ["教育の思想", "教育制度", "教育課程"] },
      { id: "shakai-fukushi", name: "社会福祉", topics: ["社会福祉制度", "児童福祉", "相談援助"] },
      { id: "jidou-fukushi", name: "児童家庭福祉", topics: ["児童福祉法", "子育て支援", "虐待防止"] },
      { id: "shinri", name: "保育の心理学", topics: ["発達心理学", "学習心理学", "臨床心理学"] },
      { id: "kodomo-hoken", name: "子どもの保健", topics: ["発育・発達", "小児疾患", "感染症予防", "応急処置"] },
      { id: "eiyo", name: "子どもの食と栄養", topics: ["栄養学基礎", "食育", "アレルギー対応", "離乳食"] },
      { id: "hoiku-jissen", name: "保育実習理論", topics: ["音楽", "造形", "言語", "保育計画"] },
    ],
  },
  // === 語学 ===
  {
    id: "toeic",
    name: "TOEIC L&R TEST",
    shortName: "TOEIC",
    description: "ビジネス英語の世界標準テスト。990点満点",
    icon: "",
    color: "#0ea5e9",
    isNational: false,
    examMonth: null,
    hasEssay: false,
    subjects: [
      { id: "listening", name: "リスニング", topics: ["写真描写", "応答問題", "会話問題", "説明文問題"] },
      { id: "reading", name: "リーディング", topics: ["短文穴埋め", "長文穴埋め", "読解問題"] },
      { id: "grammar", name: "文法", topics: ["品詞", "時制", "態", "関係詞", "比較", "仮定法"] },
      { id: "vocabulary", name: "語彙", topics: ["ビジネス語彙", "コロケーション", "イディオム"] },
    ],
  },
];

export function getExamById(id: string): ExamCategory | undefined {
  return EXAM_CATEGORIES.find((e) => e.id === id);
}

export function getExamsByType(national: boolean): ExamCategory[] {
  return EXAM_CATEGORIES.filter((e) => e.isNational === national);
}
